import { User } from "@/types/user";

export const mockUsers: User[] = [
  {
    id: "1",
    name: "Alice Smith",
    email: "alice@cipherion.com",
    role: "Admin",
    status: "Active",
    lastLogin: "12 May 2026",
    createdAt: "10 Jan 2026",
  },
  {
    id: "2",
    name: "Maria Vunina",
    email: "maria@cipherion.com",
    role: "Auditor",
    status: "Deactivated",
    lastLogin: "11 May 2026",
    createdAt: "08 Feb 2026",
  },
  {
    id: "3",
    name: "John Carter",
    email: "john@cipherion.com",
    role: "User",
    status: "Active",
    lastLogin: "09 May 2026",
    createdAt: "02 Jan 2026",
  },
  {
    id: "4",
    name: "Sarah Lee",
    email: "sarah@cipherion.com",
    role: "Admin",
    status: "Active",
    lastLogin: "08 May 2026",
    createdAt: "01 Dec 2025",
  },
  {
    id: "5",
    name: "David Kim",
    email: "david@cipherion.com",
    role: "User",
    status: "Deactivated",
    lastLogin: "07 May 2026",
    createdAt: "15 Jan 2026",
  },
  {
    id: "6",
    name: "Emma Stone",
    email: "emma@cipherion.com",
    role: "Auditor",
    status: "Active",
    lastLogin: "05 May 2026",
    createdAt: "20 Jan 2026",
  },
  {
    id: "7",
    name: "Ryan Hall",
    email: "ryan@cipherion.com",
    role: "User",
    status: "Active",
    lastLogin: "04 May 2026",
    createdAt: "28 Feb 2026",
  },
  {
    id: "8",
    name: "Sophia Clark",
    email: "sophia@cipherion.com",
    role: "Admin",
    status: "Active",
    lastLogin: "03 May 2026",
    createdAt: "01 Mar 2026",
  },
  {
    id: "9",
    name: "Daniel White",
    email: "daniel@cipherion.com",
    role: "User",
    status: "Active",
    lastLogin: "01 May 2026",
    createdAt: "05 Mar 2026",
  },
  {
    id: "10",
    name: "Olivia Brown",
    email: "olivia@cipherion.com",
    role: "Auditor",
    status: "Deactivated",
    lastLogin: "29 Apr 2026",
    createdAt: "12 Mar 2026",
  },
];
